services:
  api:
    build: {context: ., dockerfile: api/Dockerfile}
    environment:
      MODEL_VERSION: baseline-v1
      DATABASE_URL: postgresql+psycopg2://iprint:iprint@postgres:5432/iprint
      REDIS_URL: redis://redis:6379/0
    ports: ["8000:8000"]
    depends_on:
      postgres: {condition: service_healthy}
      redis: {condition: service_started}
  dashboard:
    build: {context: ., dockerfile: dashboard/Dockerfile}
    environment: {API_URL: http://api:8000}
    ports: ["8501:8501"]
    depends_on: [api]
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --allowed-hosts "*"
    volumes: [mlflow_data:/mlflow]
    ports: ["5000:5000"]
  postgres:
    image: postgres:16-alpine
    environment: {POSTGRES_DB: iprint, POSTGRES_USER: iprint, POSTGRES_PASSWORD: iprint}
    healthcheck: {test: ["CMD-SHELL","pg_isready -U iprint -d iprint"],interval: 5s,timeout: 5s,retries: 10}
    volumes: [postgres_data:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes: ["./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    ports: ["9090:9090"]
    depends_on: [api]
  grafana:
    image: grafana/grafana:11.4.0
    ports: ["3000:3000"]
    depends_on: [prometheus]
    volumes: [grafana_data:/var/lib/grafana,"./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro"]
volumes: {mlflow_data: {}, postgres_data: {}, grafana_data: {}}